// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trxekaptnzkcupbeomrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeGVrYXB0bnprY3VwYmVvbXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTczNDUsImV4cCI6MjA2MjQ3MzM0NX0.7ZN6x4WrBkNFJ4ZapW6p5cFGnY5ZMn6A4FemJ9xJ-YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);